name: flutter_sheet_localization
description: Annotations for the flutter_sheet_localization_generator package.
version: 3.0.0
homepage: https://github.com/aloisdeniel/flutter_sheet_localization

environment:
  sdk: '>=2.12.0 <3.0.0'
