name: flutter_sheet_localization
description: Annotations for the flutter_sheet_localization_generator package.
version: 1.0.0
homepage: https://github.com/aloisdeniel/flutter_sheet_localization
author: AloiÌˆs Deniel <alois.deniel@outlook.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0
